import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'coverage/**',
      'public/sw.js',
      // Build output from `opennextjs-cloudflare build` — bundled third-party code.
      '.open-next/**',
      '.wrangler/**',
      // Generated by `next build`; contains triple-slash references we do not control.
      'next-env.d.ts',
      // Generated by `wrangler types`.
      'cloudflare-env.d.ts',
      'worker-configuration.d.ts',
    ],
  },
  {
    rules: {
      // Unused variables are an error, but allow the `_`/`void` escape hatches
      // used for intentionally-discarded destructured values.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
          ignoreRestSiblings: true,
        },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'warn',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },
  {
    // Config files are allowed to log freely.
    files: ['*.config.{ts,mjs}'],
    rules: { 'no-console': 'off' },
  },
];

export default config;
