import { useAi } from '@pd/db';

import { AppError } from '../../lib/errors';
import { getAiConfig } from '../ai-providers';
import { GeminiImageEngine } from './gemini';
import { WorkersAiEngine } from './workers-ai';
import type { GeneratedImage, ImageEngine, ImageRequest } from './types';

export type { GeneratedImage, ImageEngine, ImageRequest, ReferenceImage } from './types';

/**
 * Tries the configured engine, then falls back to the other one.
 *
 * The two failure modes in practice are both quota-related and both temporary:
 * Gemini's free tier has a daily request cap, and Workers AI has a daily Neuron
 * allocation. They are separate budgets, so when one is exhausted the other
 * usually still works — which makes a fallback genuinely useful rather than
 * decorative.
 *
 * The fallback is *not* silent. `engine` on the result records what actually ran,
 * and the admin log stores it, because a cover generated by flux when the
 * operator asked for Gemini looks different and they need to know why.
 */
class ResilientImageEngine implements ImageEngine {
  readonly name: string;
  readonly supportsReference: boolean;

  constructor(
    private readonly primary: ImageEngine,
    private readonly secondary: ImageEngine | null,
  ) {
    this.name = primary.name;
    this.supportsReference = primary.supportsReference;
  }

  async generate(request: ImageRequest): Promise<GeneratedImage> {
    try {
      return await this.primary.generate(request);
    } catch (error) {
      if (!this.secondary) throw error;
      console.warn(
        `[images] ${this.primary.name} failed, trying ${this.secondary.name}:`,
        error instanceof Error ? error.message : error,
      );
      const result = await this.secondary.generate(request);
      return { ...result, engine: `${this.primary.name}-fallback:${result.engine}` };
    }
  }
}

/** True when the engine about to be used can preserve a face. */
export async function imageEngineSupportsReference(): Promise<boolean> {
  const engine = await resolveImageEngine();
  return engine.supportsReference;
}

/**
 * The configured image engine, with the other provider behind it as a fallback.
 *
 * Async now because provider, model and key all come from settings rather than
 * from `wrangler.jsonc` — see services/ai-providers.ts. Both call sites were
 * already async.
 */
export async function resolveImageEngine(): Promise<ImageEngine> {
  const c = await getAiConfig();
  const geminiReady = Boolean(c.geminiApiKey);
  const workersReady = Boolean(useAi());

  const gemini = () => new GeminiImageEngine(c.geminiApiKey, c.geminiImageModel);
  const workers = () => new WorkersAiEngine(c.workersImageModel);

  if (c.imageProvider === 'none') {
    throw AppError.badRequest(
      'Image generation is switched off. Choose an image provider on the AI providers screen.',
    );
  }

  if (c.imageProvider === 'gemini') {
    if (!geminiReady) {
      throw AppError.badRequest(
        'The image provider is set to Gemini but no Gemini API key is configured. Add one on the AI providers screen.',
      );
    }
    return new ResilientImageEngine(gemini(), workersReady ? workers() : null);
  }

  // Default: Workers AI, because it works with no key at all.
  if (!workersReady && !geminiReady) {
    throw AppError.badRequest(
      'No image provider is available. Add a Gemini API key on the AI providers screen, or bind Workers AI ("ai": { "binding": "AI" }).',
    );
  }
  if (!workersReady) return gemini();
  return new ResilientImageEngine(workers(), geminiReady ? gemini() : null);
}

/** Reported by the admin screens so operators can see what is wired up. */
export async function imageProviderStatus(): Promise<{
  provider: string;
  workersAi: boolean;
  gemini: boolean;
  supportsReference: boolean;
  model: string;
}> {
  const c = await getAiConfig();
  const workersAi = Boolean(useAi());
  const gemini = Boolean(c.geminiApiKey);
  return {
    provider: c.imageProvider,
    workersAi,
    gemini,
    // Only Gemini can hold an uploaded face, so photo-edit covers depend on it.
    supportsReference: c.imageProvider === 'gemini' ? gemini : false,
    model: c.imageProvider === 'gemini' ? c.geminiImageModel : c.workersImageModel,
  };
}
