import { useAi } from '@pd/db';

import { config } from '../../lib/env';
import { AppError } from '../../lib/errors';
import { GeminiImageEngine } from './gemini';
import { WorkersAiEngine } from './workers-ai';
import type { GeneratedImage, ImageEngine, ImageRequest } from './types';

export type { GeneratedImage, ImageEngine, ImageRequest, ReferenceImage } from './types';

/**
 * Tries the configured engine, then falls back to the other one.
 *
 * The two failure modes in practice are both quota-related and both temporary:
 * Gemini's free tier has a daily request cap, and Workers AI has a daily Neuron
 * allocation. They are separate budgets, so when one is exhausted the other
 * usually still works — which makes a fallback genuinely useful rather than
 * decorative.
 *
 * The fallback is *not* silent. `engine` on the result records what actually ran,
 * and the admin log stores it, because a cover generated by flux when the
 * operator asked for Gemini looks different and they need to know why.
 */
class ResilientImageEngine implements ImageEngine {
  readonly name: string;
  readonly supportsReference: boolean;

  constructor(
    private readonly primary: ImageEngine,
    private readonly secondary: ImageEngine | null,
  ) {
    this.name = primary.name;
    this.supportsReference = primary.supportsReference;
  }

  async generate(request: ImageRequest): Promise<GeneratedImage> {
    try {
      return await this.primary.generate(request);
    } catch (error) {
      if (!this.secondary) throw error;
      console.warn(
        `[images] ${this.primary.name} failed, trying ${this.secondary.name}:`,
        error instanceof Error ? error.message : error,
      );
      const result = await this.secondary.generate(request);
      return { ...result, engine: `${this.primary.name}-fallback:${result.engine}` };
    }
  }
}

/** True when the engine about to be used can preserve a face. */
export function imageEngineSupportsReference(): boolean {
  return resolveImageEngine().supportsReference;
}

export function resolveImageEngine(): ImageEngine {
  const c = config();
  const geminiReady = Boolean(c.aiApiKey);
  const workersReady = Boolean(useAi());

  if (c.imageProvider === 'none') {
    throw AppError.badRequest('Image generation is disabled (IMAGE_PROVIDER is "none").');
  }

  if (c.imageProvider === 'gemini') {
    if (!geminiReady) {
      throw AppError.badRequest(
        'IMAGE_PROVIDER is "gemini" but AI_API_KEY is not set. Create a free key at aistudio.google.com/apikey.',
      );
    }
    return new ResilientImageEngine(
      new GeminiImageEngine(),
      workersReady ? new WorkersAiEngine() : null,
    );
  }

  // Default: Workers AI, because it works with no key at all.
  if (!workersReady && !geminiReady) {
    throw AppError.badRequest(
      'No image provider available. Bind Workers AI ("ai": { "binding": "AI" }) or set AI_API_KEY.',
    );
  }
  if (!workersReady) return new GeminiImageEngine();
  return new ResilientImageEngine(
    new WorkersAiEngine(),
    geminiReady ? new GeminiImageEngine() : null,
  );
}

/** Reported by the admin settings screen so operators can see what is wired up. */
export function imageProviderStatus(): {
  provider: string;
  workersAi: boolean;
  gemini: boolean;
  supportsReference: boolean;
} {
  const c = config();
  const workersAi = Boolean(useAi());
  const gemini = Boolean(c.aiApiKey);
  return {
    provider: c.imageProvider,
    workersAi,
    gemini,
    supportsReference: c.imageProvider === 'gemini' ? gemini : false,
  };
}
